import { NgModule } from '@angular/core';
import {CdkTableModule} from '@angular/cdk/table';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatInputModule,
  MatCardModule,
  MatDatepickerModule,
  MatTabsModule,
  MatIconModule,
  MatSelectModule,
  MatToolbarModule,
  MatSidenavModule,
  MatMenuModule,
  MatProgressSpinnerModule,
  MatListModule,
  MatSnackBarModule,
  MatDialogModule,
  MatProgressBarModule,
  MatTooltipModule,
  MatSlideToggleModule,
  MatRadioModule,
  MatTableModule,
  MatNativeDateModule
} from '@angular/material';

@NgModule({
  imports: [
    CdkTableModule,
    MatButtonModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatCardModule,
    MatTabsModule,
    MatIconModule,
    MatSelectModule,
    MatToolbarModule,
    MatSidenavModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatSnackBarModule,
    MatDialogModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatTableModule
  ],
  exports: [
    CdkTableModule,
    MatButtonModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatCardModule,
    MatTabsModule,
    MatIconModule,
    MatSelectModule,
    MatToolbarModule,
    MatSidenavModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatSnackBarModule,
    MatDialogModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatTableModule
  ],
})
export class AngularMaterialModule { }
